[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "specMPC"
dynamic = ["version"]
authors = [
    { name = "Bruker BioSpin", email = "yen-chun.huang@bruker.com" },
]
description = "A Python package for interfacing with the Motorized Probe Controller used in Bruker spectrometers."
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "numpy >= 1.26.2",
    "pyserial >= 3.5",
]

[project.urls]
"Source Code" = "https://github.com/spinlaboratory/specMPC"

[project.scripts]
specMPC = "specMPC.cli:main"
specMPC-gui = "specMPC.gui:main"

[tool.setuptools.packages.find]
where = ["."]

[tool.setuptools.package-data]
specMPC = ["config/default_config.json"]

[tool.setuptools.dynamic]
version = { attr = "specMPC.version.__version__" }
